/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackgroundsRouteImport } from './routes/backgrounds'
import { Route as BellsRouteImport } from './routes/bells'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsRoute = BackgroundsRouteImport.update({
  id: '/backgrounds',
  path: '/backgrounds',
  getParentRoute: () => rootRouteImport,
} as any)
const BellsRoute = BellsRouteImport.update({
  id: '/bells',
  path: '/bells',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backgrounds': typeof BackgroundsRoute
  '/bells': typeof BellsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backgrounds': typeof BackgroundsRoute
  '/bells': typeof BellsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backgrounds': typeof BackgroundsRoute
  '/bells': typeof BellsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backgrounds' | '/bells'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backgrounds' | '/bells'
  id: '__root__' | '/' | '/backgrounds' | '/bells'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundsRoute: typeof BackgroundsRoute
  BellsRoute: typeof BellsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds': {
      id: '/backgrounds'
      path: '/backgrounds'
      fullPath: '/backgrounds'
      preLoaderRoute: typeof BackgroundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bells': {
      id: '/bells'
      path: '/bells'
      fullPath: '/bells'
      preLoaderRoute: typeof BellsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundsRoute: BackgroundsRoute,
  BellsRoute: BellsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
